
-- =============================================================
-- EXPANDED KNOWLEDGE GRAPH: 75 more job families
-- =============================================================

INSERT INTO public.job_taxonomy (job_family, category, disruption_baseline, india_prevalence, avg_salary_lpa, automatable_tasks, ai_tools_replacing) VALUES
-- IT & Software (more roles)
('full_stack_developer', 'IT & Software', 62, 0.08, 14.0, '["CRUD operations", "Form building", "API scaffolding", "Database migrations", "Component creation"]', '["Cursor", "Bolt", "v0.dev", "GitHub Copilot"]'),
('mobile_developer', 'IT & Software', 58, 0.06, 13.0, '["UI layouts", "API integration", "State management boilerplate", "Testing"]', '["FlutterFlow", "Cursor", "GitHub Copilot"]'),
('data_scientist', 'IT & Software', 48, 0.05, 20.0, '["EDA automation", "Feature engineering", "Model selection", "Visualization"]', '["AutoML", "DataRobot", "H2O.ai"]'),
('cloud_architect', 'IT & Software', 35, 0.03, 25.0, '["Infrastructure templating", "Cost optimization reports", "Security scanning"]', '["Pulumi AI", "AWS Bedrock"]'),
('cybersecurity_analyst', 'IT & Software', 42, 0.04, 16.0, '["Log analysis", "Threat detection", "Vulnerability scanning", "Compliance reporting"]', '["CrowdStrike AI", "Darktrace", "SentinelOne"]'),
('database_administrator', 'IT & Software', 65, 0.04, 12.0, '["Query optimization", "Backup scheduling", "Performance monitoring", "Index management"]', '["Amazon RDS AI", "OtterTune", "EverSQL"]'),
('site_reliability_engineer', 'IT & Software', 45, 0.03, 20.0, '["Incident response automation", "Runbook creation", "Capacity planning"]', '["PagerDuty AI", "Datadog AI"]'),
('embedded_systems_engineer', 'IT & Software', 30, 0.02, 14.0, '["Code documentation", "Test vector generation"]', '["GitHub Copilot"]'),
('blockchain_developer', 'IT & Software', 38, 0.01, 18.0, '["Smart contract auditing", "Test generation"]', '["OpenZeppelin AI", "Slither"]'),
('technical_writer', 'IT & Software', 80, 0.03, 7.0, '["API documentation", "User guides", "Release notes", "Knowledge base articles"]', '["ChatGPT", "Mintlify", "ReadMe AI"]'),
('solutions_architect', 'IT & Software', 32, 0.03, 22.0, '["Architecture diagrams", "Proposal drafts", "Cost estimation"]', '["AWS Well-Architected AI"]'),
('product_manager', 'IT & Software', 40, 0.05, 18.0, '["PRD drafting", "User story writing", "Competitor analysis", "Roadmap updates"]', '["Notion AI", "ProductBoard AI", "ChatGPT"]'),
('scrum_master', 'IT & Software', 55, 0.04, 12.0, '["Sprint planning docs", "Velocity reports", "Retrospective summaries"]', '["Jira AI", "Linear AI"]'),
('it_support_engineer', 'IT & Software', 75, 0.08, 5.0, '["Ticket triage", "Password resets", "Software installation", "Troubleshooting guides"]', '["Moveworks", "Freshservice AI"]'),

-- Finance & Banking (more roles)
('investment_banker', 'Finance & Banking', 45, 0.02, 25.0, '["Financial modeling", "Pitch deck creation", "Market research compilation"]', '["Bloomberg AI", "Kensho", "Tome AI"]'),
('risk_analyst', 'Finance & Banking', 58, 0.03, 12.0, '["Risk scoring", "Regulatory reports", "Scenario modeling", "Data aggregation"]', '["Moody''s AI", "SAS Viya"]'),
('insurance_underwriter', 'Finance & Banking', 72, 0.04, 8.0, '["Risk assessment", "Policy pricing", "Claims review", "Document verification"]', '["Shift Technology", "Lemonade AI"]'),
('compliance_officer', 'Finance & Banking', 55, 0.03, 14.0, '["Regulatory monitoring", "Audit trail documentation", "Policy gap analysis"]', '["Chainalysis", "ComplyAdvantage"]'),
('bank_teller', 'Finance & Banking', 90, 0.08, 3.0, '["Cash handling", "Account opening", "Balance inquiries", "Fund transfers"]', '["ATM AI", "Digital Banking Apps"]'),
('loan_officer', 'Finance & Banking', 78, 0.05, 6.0, '["Credit scoring", "Document verification", "Eligibility checks", "EMI calculation"]', '["Zest AI", "Upstart"]'),
('tax_consultant', 'Finance & Banking', 68, 0.04, 10.0, '["Tax filing", "Deduction identification", "Compliance checks", "Return preparation"]', '["TurboTax AI", "ClearTax AI"]'),

-- Marketing & Advertising (more roles)
('brand_manager', 'Marketing & Advertising', 45, 0.03, 15.0, '["Brand audit reports", "Competitive analysis", "Campaign brief drafts"]', '["Jasper", "Brandwatch AI"]'),
('performance_marketer', 'Marketing & Advertising', 70, 0.05, 10.0, '["Ad optimization", "A/B test setup", "Audience targeting", "Budget allocation"]', '["Meta Advantage+", "Google Performance Max"]'),
('social_media_manager', 'Marketing & Advertising', 78, 0.06, 5.5, '["Post scheduling", "Caption writing", "Hashtag research", "Analytics reports"]', '["Hootsuite AI", "Buffer AI", "Later AI"]'),
('market_researcher', 'Marketing & Advertising', 65, 0.03, 8.0, '["Survey design", "Data tabulation", "Report generation", "Trend analysis"]', '["SurveyMonkey AI", "Qualtrics AI"]'),
('public_relations_specialist', 'Marketing & Advertising', 58, 0.02, 8.0, '["Press release writing", "Media list building", "Coverage tracking"]', '["Meltwater AI", "Cision AI"]'),
('copywriter_senior', 'Marketing & Advertising', 55, 0.03, 10.0, '["First draft generation", "Headline variants", "Email sequences"]', '["Jasper", "Copy.ai"]'),
('media_planner', 'Marketing & Advertising', 68, 0.02, 9.0, '["Media mix modeling", "Budget allocation", "Audience analysis", "Rate negotiation docs"]', '["Google DV360 AI", "The Trade Desk AI"]'),

-- Creative & Design (more roles)
('motion_designer', 'Creative & Design', 55, 0.02, 8.0, '["Kinetic typography", "Logo animations", "Social video templates"]', '["Runway ML", "After Effects AI", "Kling"]'),
('product_designer', 'Creative & Design', 42, 0.03, 14.0, '["Wireframes", "Component variants", "Design system docs"]', '["Figma AI", "Galileo AI"]'),
('illustrator', 'Creative & Design', 50, 0.02, 6.0, '["Stock illustrations", "Icon sets", "Infographics"]', '["Midjourney", "DALL-E 3", "Adobe Firefly"]'),
('photographer', 'Creative & Design', 40, 0.03, 5.0, '["Photo editing", "Color correction", "Background removal"]', '["Adobe Lightroom AI", "Luminar AI"]'),
('3d_artist', 'Creative & Design', 45, 0.01, 10.0, '["3D modeling from text", "Texture generation", "Scene setup"]', '["Meshy AI", "Luma AI", "Kaedim"]'),
('art_director', 'Creative & Design', 30, 0.01, 16.0, '["Mood board assembly", "Style guide drafts"]', '["Midjourney"]'),

-- Healthcare (more roles)
('medical_coder', 'Healthcare', 82, 0.03, 5.0, '["Code assignment", "Chart review", "Compliance checking", "Claim processing"]', '["3M AI", "Optum AI"]'),
('lab_technician', 'Healthcare', 55, 0.04, 4.0, '["Result interpretation", "Quality control checks", "Inventory tracking"]', '["Tempus AI", "PathAI"]'),
('hospital_administrator', 'Healthcare', 50, 0.02, 12.0, '["Scheduling optimization", "Resource allocation", "Report generation"]', '["Epic AI", "Qventus"]'),
('physiotherapist', 'Healthcare', 22, 0.03, 6.0, '["Exercise plan generation", "Progress tracking"]', '["Kaia Health AI"]'),
('medical_representative', 'Healthcare', 60, 0.06, 6.0, '["Call planning", "Product detailing scripts", "Territory analysis"]', '["Veeva AI", "IQVIA AI"]'),

-- Manufacturing (more roles)
('quality_engineer', 'Manufacturing', 52, 0.03, 9.0, '["Defect classification", "SPC chart analysis", "Audit checklists"]', '["Landing AI", "Instrumental"]'),
('production_manager', 'Manufacturing', 38, 0.02, 12.0, '["Production scheduling", "Efficiency reports", "Downtime analysis"]', '["Sight Machine", "Uptake"]'),
('industrial_engineer', 'Manufacturing', 45, 0.02, 10.0, '["Time studies", "Layout optimization", "Process flow documentation"]', '["Siemens Opcenter AI"]'),
('maintenance_technician', 'Manufacturing', 35, 0.05, 5.0, '["Predictive maintenance alerts", "Work order generation"]', '["Augury", "Uptake"]'),
('procurement_specialist', 'Manufacturing', 60, 0.03, 8.0, '["Vendor comparison", "RFQ generation", "Purchase order processing"]', '["Jaggaer AI", "Coupa AI"]'),

-- Education (more roles)
('curriculum_designer', 'Education', 55, 0.02, 8.0, '["Lesson plan creation", "Assessment design", "Content structuring"]', '["Khanmigo", "Canva for Education AI"]'),
('academic_counselor', 'Education', 30, 0.02, 6.0, '["Student profiling", "College shortlisting"]', '["CollegeVine AI"]'),
('online_tutor', 'Education', 50, 0.04, 4.0, '["Content delivery", "Quiz generation", "Progress reports"]', '["Khanmigo", "Duolingo AI"]'),
('education_administrator', 'Education', 55, 0.03, 7.0, '["Timetable generation", "Attendance tracking", "Report cards"]', '["PowerSchool AI"]'),
('corporate_trainer', 'Education', 48, 0.03, 10.0, '["Training material creation", "Assessment design", "Feedback compilation"]', '["Docebo AI", "EdApp AI"]'),

-- Other / Emerging
('real_estate_agent', 'Other', 55, 0.05, 6.0, '["Property listing descriptions", "Market comparisons", "Lead qualification"]', '["Zillow AI", "REimagineHome"]'),
('journalist', 'Other', 65, 0.02, 7.0, '["News summarization", "Data journalism", "Headline writing", "Fact-checking"]', '["ChatGPT", "Perplexity", "Artifact"]'),
('event_manager', 'Other', 35, 0.03, 8.0, '["Vendor coordination docs", "Budget tracking", "Timeline creation"]', '["Notion AI", "Monday.com AI"]'),
('recruiter', 'Other', 68, 0.05, 7.0, '["Resume screening", "Outreach emails", "Candidate matching", "Interview scheduling"]', '["HireVue", "Eightfold AI", "SeekOut"]'),
('operations_manager', 'Other', 45, 0.04, 14.0, '["Process documentation", "KPI dashboards", "Vendor management reports"]', '["Notion AI", "Asana AI"]'),
('business_analyst', 'Other', 58, 0.05, 10.0, '["Requirements documentation", "Process mapping", "Gap analysis", "User story writing"]', '["ChatGPT", "Notion AI", "Lucidchart AI"]'),
('management_consultant', 'Other', 42, 0.02, 20.0, '["Market sizing", "Slide creation", "Benchmarking reports"]', '["Tome AI", "Beautiful.ai", "ChatGPT"]'),
('chartered_accountant', 'Finance & Banking', 65, 0.06, 10.0, '["Audit sampling", "Financial statement prep", "Tax computation", "Compliance filing"]', '["ClearTax AI", "TallyPrime AI"]'),
('interior_designer', 'Creative & Design', 45, 0.02, 7.0, '["Space planning", "Mood boards", "3D rendering", "Material sourcing"]', '["Planner 5D AI", "HomeDesigns AI"]'),
('logistics_coordinator', 'Other', 62, 0.04, 5.0, '["Route optimization", "Shipment tracking", "Documentation", "Inventory updates"]', '["FourKites AI", "project44"]'),
('call_center_agent', 'Other', 88, 0.12, 2.8, '["Script following", "Data entry during calls", "FAQ resolution", "Call logging"]', '["Five9 AI", "Talkdesk AI", "Genesys AI"]'),
('research_scientist', 'Other', 28, 0.02, 18.0, '["Literature review", "Data processing", "Report writing"]', '["Elicit", "Consensus AI", "Semantic Scholar"]'),
('civil_engineer', 'Manufacturing', 40, 0.04, 9.0, '["Structural calculations", "Drawing annotations", "Quantity estimation"]', '["Autodesk AI", "Tekla AI"]'),
('architect', 'Creative & Design', 38, 0.02, 12.0, '["Floor plan generation", "3D visualization", "Code compliance checks"]', '["Autodesk Forma", "Spacemaker AI"]'),
('veterinarian', 'Healthcare', 18, 0.01, 8.0, '["Medical records", "Prescription management"]', '["VetAI"]'),
('chef_culinary', 'Other', 15, 0.03, 5.0, '["Recipe documentation", "Menu costing"]', '["ChatGPT"]'),
('pilot', 'Other', 20, 0.01, 25.0, '["Flight planning", "Weather analysis", "Navigation calculations"]', '["Garmin Autoland", "ForeFlight AI"]'),
('lawyer_litigation', 'Other', 48, 0.02, 18.0, '["Case research", "Document review", "Brief drafting", "Precedent finding"]', '["Harvey AI", "CoCounsel", "Casetext"]'),
('psychologist', 'Healthcare', 15, 0.01, 10.0, '["Session notes", "Assessment scoring", "Treatment plan documentation"]', '["Woebot", "Wysa"]'),
('social_worker', 'Other', 18, 0.02, 5.0, '["Case documentation", "Resource matching"]', '["Casebook AI"]'),
('fitness_trainer', 'Other', 30, 0.04, 4.0, '["Workout plan generation", "Diet planning", "Progress tracking"]', '["FitnessAI", "Trainerize AI"]');

-- =============================================================
-- EXPANDED SKILLS: 70+ more skills
-- =============================================================

INSERT INTO public.skill_risk_matrix (skill_name, category, automation_risk, ai_augmentation_potential, india_demand_trend, replacement_tools, human_moat, learning_curve) VALUES
-- Engineering skills
('mobile_development', 'engineering', 58, 82, 'stable', '{"FlutterFlow", "Cursor"}', 'Platform-specific optimization', 'high'),
('devops', 'engineering', 50, 85, 'rising', '{"GitHub Actions AI", "Pulumi AI"}', 'Incident judgment', 'high'),
('cloud_infrastructure', 'engineering', 45, 80, 'rising', '{"Pulumi AI", "AWS CDK AI"}', 'Cost-performance tradeoffs', 'high'),
('data_engineering', 'engineering', 52, 82, 'rising', '{"dbt AI", "Fivetran"}', 'Pipeline architecture decisions', 'high'),
('machine_learning', 'engineering', 35, 90, 'rising', '{"AutoML", "H2O.ai"}', 'Problem framing & feature intuition', 'high'),
('cybersecurity', 'engineering', 40, 75, 'rising', '{"CrowdStrike AI", "Darktrace"}', 'Adversarial thinking', 'high'),
('api_development', 'engineering', 60, 85, 'stable', '{"Cursor", "GitHub Copilot"}', 'API design philosophy', 'medium'),
('database_management', 'engineering', 62, 78, 'stable', '{"OtterTune", "EverSQL"}', 'Performance intuition', 'medium'),
('embedded_programming', 'engineering', 28, 60, 'stable', '{"GitHub Copilot"}', 'Hardware-software integration', 'high'),
('system_design', 'engineering', 25, 75, 'rising', '{}', 'Tradeoff analysis at scale', 'high'),

-- Content & Communication
('technical_writing', 'content', 78, 82, 'falling', '{"Mintlify", "ReadMe AI"}', NULL, 'medium'),
('video_production', 'creative', 52, 75, 'stable', '{"Runway ML", "Descript"}', 'Narrative storytelling', 'medium'),
('podcasting', 'content', 35, 70, 'rising', '{"Descript", "Riverside AI"}', 'Authentic voice', 'low'),
('presentation_design', 'content', 72, 80, 'stable', '{"Tome AI", "Beautiful.ai", "Gamma"}', NULL, 'low'),
('translation', 'content', 80, 75, 'falling', '{"DeepL", "Google Translate AI"}', NULL, 'medium'),
('academic_writing', 'content', 65, 70, 'stable', '{"ChatGPT", "Elicit"}', 'Original research insight', 'high'),
('journalism', 'content', 60, 65, 'falling', '{"Artifact", "Perplexity"}', 'Source relationships & investigation', 'high'),

-- Business & Management
('business_development', 'business', 35, 70, 'rising', '{"Apollo.io", "Outreach AI"}', 'Deal intuition & trust', 'high'),
('supply_chain_management', 'business', 52, 72, 'stable', '{"Blue Yonder", "o9 Solutions"}', 'Vendor relationship judgment', 'high'),
('human_resources', 'business', 55, 65, 'stable', '{"Eightfold AI", "HireVue"}', 'People judgment', 'medium'),
('event_planning', 'business', 32, 55, 'stable', '{}', 'On-the-ground coordination', 'medium'),
('consulting', 'business', 40, 70, 'stable', '{"ChatGPT", "Tome AI"}', 'Client trust & boardroom presence', 'high'),
('recruitment', 'business', 65, 72, 'stable', '{"SeekOut", "Eightfold AI"}', 'Candidate rapport', 'medium'),
('customer_success', 'business', 45, 65, 'rising', '{"Gainsight AI", "Totango"}', 'Empathetic problem-solving', 'medium'),
('procurement', 'business', 58, 65, 'stable', '{"Jaggaer AI", "Coupa AI"}', 'Vendor negotiation', 'medium'),
('operations', 'business', 48, 68, 'stable', '{"Monday.com AI", "Asana AI"}', 'Cross-team coordination', 'medium'),

-- Finance
('investment_analysis', 'finance', 55, 78, 'stable', '{"Bloomberg AI", "Kensho"}', 'Market conviction', 'high'),
('tax_preparation', 'finance', 75, 70, 'falling', '{"TurboTax AI", "ClearTax AI"}', NULL, 'medium'),
('audit', 'finance', 62, 68, 'stable', '{"MindBridge AI", "Caseware AI"}', 'Professional skepticism', 'high'),
('insurance_underwriting', 'finance', 72, 65, 'falling', '{"Shift Technology", "Lemonade AI"}', NULL, 'medium'),
('credit_analysis', 'finance', 70, 70, 'falling', '{"Zest AI", "Upstart"}', NULL, 'medium'),
('compliance', 'finance', 55, 60, 'rising', '{"ComplyAdvantage", "Chainalysis"}', 'Regulatory judgment', 'high'),

-- Creative
('illustration', 'creative', 52, 78, 'falling', '{"Midjourney", "DALL-E 3"}', 'Personal artistic style', 'high'),
('animation', 'creative', 48, 75, 'stable', '{"Runway ML", "Kling"}', 'Timing & emotional impact', 'high'),
('photography', 'creative', 38, 65, 'stable', '{"Luminar AI", "Topaz AI"}', 'Moment capture', 'medium'),
('interior_design', 'creative', 42, 72, 'stable', '{"Planner 5D AI", "HomeDesigns AI"}', 'Spatial intuition', 'high'),
('ux_research', 'creative', 35, 70, 'rising', '{"Maze AI", "UserTesting AI"}', 'Human behavior insight', 'high'),
('industrial_design', 'creative', 40, 70, 'stable', '{"Autodesk Fusion AI"}', 'Form-function innovation', 'high'),

-- Healthcare
('medical_coding', 'healthcare', 82, 60, 'falling', '{"3M AI", "Optum AI"}', NULL, 'medium'),
('patient_care', 'healthcare', 8, 35, 'rising', '{}', 'Physical presence & compassion', 'high'),
('diagnostics', 'healthcare', 35, 80, 'rising', '{"Google Med-PaLM", "PathAI"}', 'Clinical gestalt', 'high'),
('pharmacy', 'healthcare', 52, 60, 'stable', '{"PioneerRx AI"}', 'Patient counseling', 'high'),
('medical_research', 'healthcare', 30, 85, 'rising', '{"Elicit", "Consensus AI"}', 'Hypothesis generation', 'high'),

-- Education
('curriculum_development', 'education', 52, 72, 'stable', '{"Khanmigo", "Canva Education AI"}', 'Pedagogical philosophy', 'high'),
('academic_counseling', 'education', 28, 55, 'rising', '{"CollegeVine AI"}', 'Student emotional support', 'high'),
('corporate_training', 'education', 50, 68, 'stable', '{"Docebo AI", "EdApp AI"}', 'Adult learning facilitation', 'medium'),
('online_content_creation', 'education', 58, 75, 'stable', '{"Synthesia", "Descript"}', NULL, 'medium'),

-- Legal
('legal_research', 'other', 72, 80, 'stable', '{"Harvey AI", "CoCounsel"}', NULL, 'high'),
('contract_drafting', 'other', 68, 78, 'stable', '{"Ironclad AI", "SpotDraft"}', 'Risk anticipation', 'high'),
('litigation_support', 'other', 55, 70, 'stable', '{"Casetext", "ROSS Intelligence"}', 'Courtroom strategy', 'high'),

-- Miscellaneous
('logistics', 'operations', 60, 68, 'stable', '{"FourKites AI", "project44"}', NULL, 'medium'),
('real_estate', 'business', 52, 60, 'stable', '{"Zillow AI", "REimagineHome"}', 'Local market intuition', 'medium'),
('fitness_coaching', 'healthcare', 30, 55, 'rising', '{"FitnessAI", "Trainerize AI"}', 'Motivation & accountability', 'medium'),
('public_speaking', 'communication', 12, 50, 'rising', '{}', 'Charisma & presence', 'high'),
('research', 'other', 45, 82, 'rising', '{"Elicit", "Consensus AI", "Perplexity"}', 'Original hypothesis formulation', 'high'),
('data_visualization', 'analytics', 68, 80, 'stable', '{"Tableau AI", "PowerBI Copilot"}', NULL, 'medium'),
('excel_advanced', 'analytics', 78, 75, 'falling', '{"ChatGPT", "SheetAI"}', NULL, 'low'),
('erp_management', 'operations', 55, 60, 'stable', '{"SAP Joule", "Oracle AI"}', 'Process customization expertise', 'high'),
('quality_assurance', 'operations', 58, 65, 'stable', '{"Landing AI", "Instrumental"}', 'Defect pattern recognition', 'medium'),
('social_media_content', 'content', 76, 72, 'stable', '{"Jasper", "Canva AI", "CapCut AI"}', NULL, 'low'),
('customer_service', 'operations', 82, 55, 'falling', '{"Zendesk AI", "Intercom Fin", "Ada AI"}', NULL, 'low'),
('cold_calling', 'business', 55, 60, 'falling', '{"Orum AI", "Dialpad AI"}', 'Rapport in seconds', 'low'),
('market_analysis', 'business', 60, 75, 'stable', '{"ChatGPT", "Perplexity", "Alphasense"}', 'Contrarian insight', 'high');

-- =============================================================
-- EXPANDED JOB-SKILL MAPPINGS
-- =============================================================

INSERT INTO public.job_skill_map (job_family, skill_name, importance, frequency) VALUES
('full_stack_developer', 'frontend_development', 0.80, 'daily'),
('full_stack_developer', 'backend_development', 0.80, 'daily'),
('full_stack_developer', 'database_management', 0.60, 'daily'),
('full_stack_developer', 'api_development', 0.75, 'daily'),
('mobile_developer', 'mobile_development', 0.95, 'daily'),
('mobile_developer', 'api_development', 0.50, 'weekly'),
('data_scientist', 'machine_learning', 0.90, 'daily'),
('data_scientist', 'data_visualization', 0.70, 'daily'),
('data_scientist', 'sql_queries', 0.65, 'daily'),
('cloud_architect', 'cloud_infrastructure', 0.95, 'daily'),
('cloud_architect', 'system_design', 0.85, 'daily'),
('cloud_architect', 'solution_architecture', 0.80, 'weekly'),
('cybersecurity_analyst', 'cybersecurity', 0.95, 'daily'),
('cybersecurity_analyst', 'cloud_infrastructure', 0.40, 'weekly'),
('database_administrator', 'database_management', 0.95, 'daily'),
('database_administrator', 'sql_queries', 0.90, 'daily'),
('site_reliability_engineer', 'devops', 0.90, 'daily'),
('site_reliability_engineer', 'cloud_infrastructure', 0.75, 'daily'),
('site_reliability_engineer', 'system_design', 0.60, 'weekly'),
('technical_writer', 'technical_writing', 0.95, 'daily'),
('technical_writer', 'email_writing', 0.50, 'daily'),
('solutions_architect', 'solution_architecture', 0.95, 'daily'),
('solutions_architect', 'system_design', 0.80, 'daily'),
('solutions_architect', 'strategic_thinking', 0.60, 'weekly'),
('product_manager', 'product_vision', 0.85, 'daily'),
('product_manager', 'strategic_thinking', 0.70, 'daily'),
('product_manager', 'cross_functional_leadership', 0.65, 'daily'),
('scrum_master', 'project_management', 0.85, 'daily'),
('scrum_master', 'team_leadership', 0.70, 'daily'),
('it_support_engineer', 'customer_service', 0.80, 'daily'),
('it_support_engineer', 'l1_support', 0.90, 'daily'),
('investment_banker', 'investment_analysis', 0.90, 'daily'),
('investment_banker', 'financial_modeling', 0.85, 'daily'),
('investment_banker', 'negotiation', 0.70, 'weekly'),
('investment_banker', 'presentation_design', 0.60, 'weekly'),
('risk_analyst', 'financial_modeling', 0.70, 'daily'),
('risk_analyst', 'compliance', 0.65, 'daily'),
('risk_analyst', 'data_visualization', 0.50, 'weekly'),
('insurance_underwriter', 'insurance_underwriting', 0.95, 'daily'),
('insurance_underwriter', 'credit_analysis', 0.50, 'daily'),
('compliance_officer', 'compliance', 0.95, 'daily'),
('compliance_officer', 'ethical_judgment', 0.70, 'daily'),
('bank_teller', 'customer_service', 0.90, 'daily'),
('bank_teller', 'data_entry', 0.80, 'daily'),
('loan_officer', 'credit_analysis', 0.90, 'daily'),
('loan_officer', 'customer_service', 0.60, 'daily'),
('tax_consultant', 'tax_preparation', 0.95, 'daily'),
('tax_consultant', 'compliance', 0.70, 'daily'),
('chartered_accountant', 'audit', 0.80, 'daily'),
('chartered_accountant', 'tax_preparation', 0.70, 'daily'),
('chartered_accountant', 'compliance', 0.65, 'weekly'),
('brand_manager', 'brand_storytelling', 0.85, 'daily'),
('brand_manager', 'strategic_thinking', 0.75, 'daily'),
('brand_manager', 'market_analysis', 0.60, 'weekly'),
('performance_marketer', 'seo_optimization', 0.70, 'daily'),
('performance_marketer', 'data_visualization', 0.55, 'daily'),
('performance_marketer', 'market_analysis', 0.50, 'weekly'),
('social_media_manager', 'social_media_management', 0.90, 'daily'),
('social_media_manager', 'social_media_content', 0.85, 'daily'),
('social_media_manager', 'basic_copywriting', 0.70, 'daily'),
('market_researcher', 'market_analysis', 0.90, 'daily'),
('market_researcher', 'data_visualization', 0.70, 'daily'),
('market_researcher', 'report_generation', 0.80, 'daily'),
('recruiter', 'recruitment', 0.95, 'daily'),
('recruiter', 'email_writing', 0.70, 'daily'),
('recruiter', 'client_relationship_management', 0.60, 'daily'),
('business_analyst', 'report_generation', 0.80, 'daily'),
('business_analyst', 'data_visualization', 0.65, 'daily'),
('business_analyst', 'strategic_thinking', 0.55, 'weekly'),
('journalist', 'journalism', 0.90, 'daily'),
('journalist', 'research', 0.70, 'daily'),
('management_consultant', 'consulting', 0.90, 'daily'),
('management_consultant', 'strategic_thinking', 0.85, 'daily'),
('management_consultant', 'presentation_design', 0.70, 'daily'),
('call_center_agent', 'customer_service', 0.95, 'daily'),
('call_center_agent', 'cold_calling', 0.70, 'daily'),
('motion_designer', 'animation', 0.90, 'daily'),
('motion_designer', 'video_production', 0.70, 'daily'),
('product_designer', 'ux_research', 0.75, 'daily'),
('product_designer', 'creative_direction', 0.65, 'daily'),
('product_designer', 'graphic_design', 0.80, 'daily'),
('medical_coder', 'medical_coding', 0.95, 'daily'),
('medical_coder', 'data_entry', 0.60, 'daily'),
('hospital_administrator', 'operations', 0.80, 'daily'),
('hospital_administrator', 'team_leadership', 0.70, 'daily'),
('physiotherapist', 'patient_care', 0.95, 'daily'),
('physiotherapist', 'empathy_care', 0.85, 'daily'),
('quality_engineer', 'quality_assurance', 0.90, 'daily'),
('production_manager', 'team_leadership', 0.80, 'daily'),
('production_manager', 'operations', 0.85, 'daily'),
('logistics_coordinator', 'logistics', 0.90, 'daily'),
('logistics_coordinator', 'data_entry', 0.60, 'daily'),
('curriculum_designer', 'curriculum_development', 0.95, 'daily'),
('curriculum_designer', 'teaching', 0.50, 'weekly'),
('corporate_trainer', 'corporate_training', 0.90, 'daily'),
('corporate_trainer', 'public_speaking', 0.75, 'daily'),
('lawyer_litigation', 'litigation_support', 0.85, 'daily'),
('lawyer_litigation', 'legal_research', 0.80, 'daily'),
('lawyer_litigation', 'negotiation', 0.70, 'weekly'),
('real_estate_agent', 'real_estate', 0.90, 'daily'),
('real_estate_agent', 'negotiation', 0.80, 'daily'),
('real_estate_agent', 'client_relationship_management', 0.75, 'daily'),
('fitness_trainer', 'fitness_coaching', 0.95, 'daily'),
('fitness_trainer', 'empathy_care', 0.50, 'daily'),
('psychologist', 'empathy_care', 0.95, 'daily'),
('psychologist', 'mentorship', 0.70, 'daily'),
('research_scientist', 'research', 0.90, 'daily'),
('research_scientist', 'medical_research', 0.75, 'daily'),
('research_scientist', 'academic_writing', 0.70, 'weekly'),
('operations_manager', 'operations', 0.90, 'daily'),
('operations_manager', 'team_leadership', 0.75, 'daily'),
('operations_manager', 'cross_functional_leadership', 0.65, 'daily'),
('event_manager', 'event_planning', 0.90, 'daily'),
('event_manager', 'client_relationship_management', 0.70, 'daily'),
('architect', 'industrial_design', 0.60, 'daily'),
('architect', 'creative_direction', 0.70, 'daily'),
('civil_engineer', 'system_design', 0.40, 'weekly'),
('pilot', 'strategic_thinking', 0.30, 'daily'),
('social_worker', 'empathy_care', 0.95, 'daily'),
('social_worker', 'crisis_management', 0.70, 'weekly'),
('veterinarian', 'clinical_judgment', 0.80, 'daily'),
('veterinarian', 'empathy_care', 0.85, 'daily');

-- =============================================================
-- EXPANDED MARKET SIGNALS
-- =============================================================

INSERT INTO public.market_signals (job_family, metro_tier, posting_volume_30d, posting_change_pct, avg_salary_change_pct, ai_job_mentions_pct, market_health) VALUES
('full_stack_developer', 'tier1', 5500, -15.0, -4.0, 42.0, 'declining'),
('full_stack_developer', 'tier2', 2000, -6.0, -1.0, 20.0, 'stable'),
('mobile_developer', 'tier1', 3800, -10.0, -2.0, 30.0, 'stable'),
('mobile_developer', 'tier2', 1400, -3.0, 0.0, 15.0, 'stable'),
('data_scientist', 'tier1', 4500, 15.0, 8.0, 72.0, 'booming'),
('data_scientist', 'tier2', 1200, 8.0, 3.0, 50.0, 'booming'),
('cloud_architect', 'tier1', 3000, 20.0, 10.0, 35.0, 'booming'),
('cloud_architect', 'tier2', 800, 10.0, 5.0, 20.0, 'booming'),
('cybersecurity_analyst', 'tier1', 2800, 25.0, 12.0, 28.0, 'booming'),
('cybersecurity_analyst', 'tier2', 900, 12.0, 5.0, 15.0, 'booming'),
('database_administrator', 'tier1', 1800, -20.0, -8.0, 35.0, 'declining'),
('database_administrator', 'tier2', 700, -10.0, -3.0, 18.0, 'declining'),
('technical_writer', 'tier1', 1200, -35.0, -12.0, 58.0, 'declining'),
('technical_writer', 'tier2', 400, -15.0, -5.0, 30.0, 'declining'),
('product_manager', 'tier1', 4200, 8.0, 5.0, 22.0, 'booming'),
('product_manager', 'tier2', 1500, 5.0, 2.0, 12.0, 'stable'),
('solutions_architect', 'tier1', 2500, 12.0, 8.0, 25.0, 'booming'),
('scrum_master', 'tier1', 2000, -12.0, -5.0, 20.0, 'declining'),
('it_support_engineer', 'tier1', 3500, -30.0, -15.0, 55.0, 'declining'),
('it_support_engineer', 'tier2', 2500, -18.0, -8.0, 30.0, 'declining'),
('investment_banker', 'tier1', 1200, 3.0, 5.0, 15.0, 'stable'),
('risk_analyst', 'tier1', 1500, -5.0, -2.0, 22.0, 'stable'),
('insurance_underwriter', 'tier1', 800, -25.0, -10.0, 40.0, 'declining'),
('bank_teller', 'tier1', 2000, -45.0, -20.0, 60.0, 'declining'),
('bank_teller', 'tier2', 3000, -30.0, -12.0, 35.0, 'declining'),
('loan_officer', 'tier1', 1500, -28.0, -10.0, 42.0, 'declining'),
('tax_consultant', 'tier1', 1800, -15.0, -5.0, 25.0, 'declining'),
('chartered_accountant', 'tier1', 2200, -10.0, -3.0, 20.0, 'stable'),
('brand_manager', 'tier1', 1800, 5.0, 3.0, 18.0, 'stable'),
('performance_marketer', 'tier1', 2500, -20.0, -8.0, 50.0, 'declining'),
('social_media_manager', 'tier1', 1800, -28.0, -12.0, 55.0, 'declining'),
('recruiter', 'tier1', 2800, -22.0, -8.0, 45.0, 'declining'),
('recruiter', 'tier2', 1500, -10.0, -3.0, 22.0, 'declining'),
('business_analyst', 'tier1', 3200, -8.0, -2.0, 25.0, 'stable'),
('business_analyst', 'tier2', 1800, -3.0, 0.0, 12.0, 'stable'),
('management_consultant', 'tier1', 1500, 5.0, 5.0, 18.0, 'stable'),
('call_center_agent', 'tier1', 6000, -40.0, -20.0, 72.0, 'declining'),
('call_center_agent', 'tier2', 8000, -25.0, -12.0, 45.0, 'declining'),
('motion_designer', 'tier1', 1200, -12.0, -5.0, 38.0, 'declining'),
('product_designer', 'tier1', 2500, 8.0, 5.0, 25.0, 'stable'),
('medical_coder', 'tier1', 1500, -22.0, -10.0, 40.0, 'declining'),
('journalist', 'tier1', 800, -30.0, -15.0, 55.0, 'declining'),
('real_estate_agent', 'tier1', 2000, -5.0, 0.0, 15.0, 'stable'),
('logistics_coordinator', 'tier1', 2500, -12.0, -5.0, 30.0, 'declining'),
('research_scientist', 'tier1', 1800, 15.0, 8.0, 40.0, 'booming'),
('civil_engineer', 'tier1', 2200, -5.0, -2.0, 12.0, 'stable'),
('architect', 'tier1', 1500, -3.0, 0.0, 18.0, 'stable'),
('lawyer_litigation', 'tier1', 1800, -5.0, 0.0, 20.0, 'stable'),
('psychologist', 'tier1', 800, 10.0, 5.0, 8.0, 'booming'),
('fitness_trainer', 'tier1', 1500, 5.0, 2.0, 10.0, 'stable');
