import { useNavigate } from 'react-router-dom';
import { ArrowLeft, ExternalLink, Shield, Brain, BarChart3, Clock, BookOpen } from 'lucide-react';
import SEO from '@/components/SEO';

/**
 * /methodology — How JobBachao's scoring works.
 * Audit finding: product claimed "live market data" and cited McKinsey/WEF/NASSCOM
 * in code comments but nowhere visible to users. Trust signals need to be public.
 * This page makes the methodology transparent, citable, and fact-checkable.
 */
export default function Methodology() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <SEO
        title="Methodology — How JobBachao's AI Career Risk Score Works"
        description="Transparent breakdown of how the JobBachao Career Position Score is computed: 98 role archetypes, 30 skill categories, real-time India market signals and deterministic scoring."
        canonical="https://jobbachao.com/methodology"
      />
      {/* Header */}
      <div className="border-b border-border/50 bg-background/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-4 py-4 flex items-center gap-3">
          <button
            onClick={() => navigate('/')}
            className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back
          </button>
          <span className="text-border/60">|</span>
          <span className="text-sm font-bold text-foreground">How the Score Works</span>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-12 space-y-14">

        {/* Hero */}
        <div>
          <div className="text-[11px] font-black uppercase tracking-widest text-primary mb-3">Methodology</div>
          <h1 className="text-3xl sm:text-4xl font-black text-foreground leading-tight mb-4">
            How JobBachao calculates your career risk score
          </h1>
          <p className="text-base text-muted-foreground leading-relaxed">
            We believe trust is the product. This page explains every component of the Career Position Score — what data it uses, where that data comes from, and what it cannot tell you. If something seems off about your score, this is the place to understand why.
          </p>
        </div>

        {/* Score overview */}
        <div className="rounded-2xl border-2 border-border p-6 space-y-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
              <Brain className="w-5 h-5 text-primary" />
            </div>
            <div>
              <h2 className="text-lg font-black text-foreground">The Career Position Score</h2>
              <p className="text-sm text-muted-foreground">A composite index from 0–100 (lower = more exposed to AI displacement)</p>
            </div>
          </div>
          <p className="text-sm text-foreground/80 leading-relaxed">
            The score is <strong>deterministic</strong> — the same inputs always produce the same score. It is not generated by an AI language model and does not change based on what phrasing you use. It is computed from five measurable factors:
          </p>
          <div className="grid sm:grid-cols-2 gap-3">
            {[
              { label: 'Role automation risk', weight: '~45%', desc: 'How automatable your specific job tasks are, matched against 98 role archetypes spanning IT, finance, marketing, BPO/KPO, healthcare, government, and more' },
              { label: 'Skill-level risk', weight: '~25%', desc: 'Each of your skills matched against our Knowledge Graph — execution skills vs strategic skills' },
              { label: 'Experience & seniority', weight: '~15%', desc: 'More experience = lower risk for the same role. Executive roles are scored differently.' },
              { label: 'Market signals', weight: '~10%', desc: 'Live job posting trends for your role — is hiring growing or declining?' },
              { label: 'Company health', weight: '~5%', desc: 'Current health of your employer — a struggling company amplifies your risk' },
            ].map((item) => (
              <div key={item.label} className="rounded-xl bg-muted/30 p-3.5">
                <div className="flex items-center justify-between mb-1">
                  <p className="text-xs font-black text-foreground">{item.label}</p>
                  <span className="text-[10px] font-bold text-primary bg-primary/10 px-2 py-0.5 rounded-full">{item.weight}</span>
                </div>
                <p className="text-[11px] text-muted-foreground leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Knowledge Graph */}
        <div className="space-y-4">
          <h2 className="text-xl font-black text-foreground flex items-center gap-2">
            <Shield className="w-5 h-5 text-primary" />
            The Knowledge Graph
          </h2>
          <p className="text-sm text-foreground/80 leading-relaxed">
            The Knowledge Graph is JobBachao's structured database of how automatable different jobs and skills are. It currently contains <strong>98 role archetypes</strong>, <strong>30 skill categories</strong>, <strong>20 industry sectors</strong>, and <strong>10 named AI tool threats</strong> tracked by deployment stage.
          </p>
          <p className="text-sm text-foreground/80 leading-relaxed">
            Each role node contains: base automation probability, task automatability score, social intelligence requirement, creative originality requirement, decision authority level, regulatory shield strength, and displacement timeline estimates.
          </p>
          <div className="rounded-xl bg-muted/30 border border-border p-4 space-y-2">
            <p className="text-xs font-black text-foreground uppercase tracking-wider">Data Sources</p>
            <ul className="space-y-1.5">
              {[
                { src: 'Frey & Osborne (2013)', desc: '"The Future of Employment" — Oxford University. The foundational occupational task analysis framework.' },
                { src: 'McKinsey GenAI Impact Report (2024)', desc: 'Updated role-level automation risk with generative AI context.' },
                { src: 'WEF Future of Jobs Report (2025)', desc: 'Sectoral displacement timelines and skill transition forecasts.' },
                { src: 'NASSCOM India Tech Workforce Study (2024)', desc: 'India-specific IT sector displacement data and BPO/KPO risk analysis.' },
                { src: 'O*NET Task Database', desc: 'US-sourced task-level decomposition, used as reference and adjusted for Indian market.' },
                { src: 'LinkedIn India Workforce Insights (2025)', desc: 'Hiring trends, skill demand signals, salary bands by city and role.' },
                { src: 'Live job posting signals via Adzuna India API', desc: 'Real-time job posting volume and salary trend data, updated weekly.' },
              ].map((item) => (
                <li key={item.src} className="flex gap-2.5 text-xs">
                  <span className="text-primary font-bold flex-shrink-0 mt-0.5">→</span>
                  <span><strong className="text-foreground">{item.src}</strong> — <span className="text-muted-foreground">{item.desc}</span></span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Doom Clock */}
        <div className="space-y-4">
          <h2 className="text-xl font-black text-foreground flex items-center gap-2">
            <Clock className="w-5 h-5 text-amber-400" />
            The Adaptation Window
          </h2>
          <p className="text-sm text-foreground/80 leading-relaxed">
            This is <strong>not</strong> a "months until you lose your job" counter. It is the estimated time before AI-driven disruption meaningfully affects hiring, compensation, or role requirements in your field.
          </p>
          <p className="text-sm text-foreground/80 leading-relaxed">
            The timeline is calculated from two sources: (1) your role's displacement timeline from the Knowledge Graph (when available with high confidence), blended with (2) a deterministic formula derived from your overall risk score. The formula is calibrated against the WEF's phased displacement model: partial displacement (20-30% of tasks) → significant displacement (50%+) → critical restructuring.
          </p>
          <div className="rounded-xl border border-amber-400/20 bg-amber-400/[0.04] p-4">
            <p className="text-xs font-semibold text-foreground/70 leading-relaxed">
              <strong className="text-foreground">Important:</strong> These timelines are estimates based on current AI adoption trajectories. The actual pace of displacement depends on factors outside any model: regulatory developments, economic conditions, employer-specific AI adoption decisions, and breakthrough AI capabilities. The window shown represents a planning horizon, not a prediction.
            </p>
          </div>
        </div>

        {/* Salary bleed */}
        <div className="space-y-4">
          <h2 className="text-xl font-black text-foreground flex items-center gap-2">
            <BarChart3 className="w-5 h-5 text-destructive" />
            Salary Impact Estimates
          </h2>
          <p className="text-sm text-foreground/80 leading-relaxed">
            The salary depreciation estimates shown in the product are directional indicators, not predictions. They model the estimated annual salary pressure for your role at your risk level, based on observed patterns in the Indian IT and services labour market (2022–2024).
          </p>
          <div className="rounded-xl border border-destructive/20 bg-destructive/[0.04] p-4">
            <p className="text-xs font-semibold text-foreground/70 leading-relaxed">
              <strong className="text-foreground">Limitation we acknowledge:</strong> The salary impact formula is calibrated against observed salary compression in Indian IT services roles and should be treated as directional guidance. It does not account for individual salary negotiation, role transitions, or company-specific factors. We are working to incorporate longitudinal salary data from Indian job platforms to improve this estimate.
            </p>
          </div>
        </div>

        {/* India calibration */}
        <div className="space-y-4">
          <h2 className="text-xl font-black text-foreground">India Market Calibration</h2>
          <p className="text-sm text-foreground/80 leading-relaxed">
            Most global AI displacement research is calibrated to US and European labour markets. JobBachao applies India-specific adjustments throughout:
          </p>
          <ul className="space-y-2">
            {[
              'IT services and outsourcing roles are scored with a higher automation floor (62 vs global 48) to reflect the acute displacement already underway in the sector.',
              'BPO/KPO roles are scored as already in the yellow zone — displacement is not theoretical, it is current.',
              'City-tier adjustments account for differential AI adoption rates: Bangalore and Hyderabad score significantly higher on AI adoption multiplier than tier-2 cities.',
              'Salary anchors are in ₹ INR, with city-specific ranges (e.g., ₹18-28L in Bangalore vs ₹12-18L in Pune for the same role).',
              'The product recognises domestic India relocation (e.g., tier-2 → Bangalore) as a real optionality — not just international moves.',
            ].map((item, i) => (
              <li key={i} className="flex gap-2.5 text-sm text-foreground/80">
                <span className="text-primary font-black flex-shrink-0">•</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* What the score cannot tell you */}
        <div className="space-y-4">
          <h2 className="text-xl font-black text-foreground">What the score cannot tell you</h2>
          <div className="grid sm:grid-cols-2 gap-3">
            {[
              'Whether you personally will lose your job (it measures role-level risk, not individual circumstances)',
              'Your employer\'s specific AI adoption plans or hiring decisions',
              'Whether a particular company will lay off or hire in your role',
              'The outcome of your specific salary negotiation',
              'Whether your score will go up or down after you take a course',
            ].map((item, i) => (
              <div key={i} className="flex gap-2.5 text-sm text-foreground/75 bg-muted/30 rounded-xl p-3">
                <span className="text-muted-foreground font-black flex-shrink-0">✕</span>
                <span>{item}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Research links */}
        <div className="space-y-4">
          <h2 className="text-xl font-black text-foreground flex items-center gap-2">
            <BookOpen className="w-5 h-5 text-primary" />
            Key Research
          </h2>
          <div className="space-y-2">
            {[
              { title: 'The Future of Employment — Frey & Osborne, Oxford (2013)', url: 'https://www.ox.ac.uk/news/2013-09-17-oxford-martin-school-study-shows-nearly-half-us-jobs-could-be-risk-computerisation' },
              { title: 'The Economic Potential of Generative AI — McKinsey (2023)', url: 'https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/the-economic-potential-of-generative-ai' },
              { title: 'Future of Jobs Report 2025 — World Economic Forum', url: 'https://www.weforum.org/publications/the-future-of-jobs-report-2025/' },
              { title: 'NASSCOM India Technology Sector Snapshot 2024', url: 'https://nasscom.in/knowledge-center/publications/technology-sector-in-india-2024' },
            ].map((item) => (
              <a
                key={item.title}
                href={item.url}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-2 text-sm text-primary hover:text-primary/80 underline underline-offset-2 decoration-primary/40"
              >
                <ExternalLink className="w-3.5 h-3.5 flex-shrink-0" />
                {item.title}
              </a>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="pt-6 border-t border-border text-center">
          <p className="text-xs text-muted-foreground">
            Questions about the methodology? Email us at{' '}
            <a href="mailto:hello@jobbachao.com" className="text-primary hover:underline">hello@jobbachao.com</a>
          </p>
        </div>

      </div>
    </div>
  );
}
